# Generated by Django 4.1.5 on 2023-01-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'География',
                'verbose_name_plural': 'География',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='profession_img/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='RelevancePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Востребованность',
                'verbose_name_plural': 'Востребованность',
            },
        ),
        migrations.CreateModel(
            name='SkillPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Навыки',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('csv_file', models.FileField(upload_to='csv/', verbose_name='Файл .csv')),
                ('img_file', models.ImageField(upload_to='charts/', verbose_name='График')),
                ('geo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.geopage')),
                ('relevance_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.relevancepage')),
                ('skill_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.skillpage')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
    ]
